---
title: "Untitled"
author: "Avery"
date: "3/16/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE}
library(dplyr)
library(spotifyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(glmnet)
library(caret)
```

 ```{r}
id <- '29dd370f3d934a20999183b22e985a7b'
secret <- "84fd28b593d84527bcafcfb0adab6106"
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
```


```{r}
dpath = "clean_data//trackData.csv"
data = read.csv(dpath) 
cols_to_keep = c("song_name","artist_name","danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence","tempo")


# data <- read.csv("clean_data//trackData.csv")
# cols_to_keep <- c("song_name","artist_name","danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence","tempo")

# #training_data <- data #%>% group_by_at(cols_to_keep)  #summarise(avg_rank = mean(ranking), weeks_trending = n()) %>% mutate(avg_rank_per_week = avg_rank/weeks_trending)# training data

s = sample(c(0,1), replace=1, prob = c(0.7,0.2) , size = nrow(data))
train = data
train$sample  = s
test = subset(train, sample==0)
train = subset(train, sample!=0)


```

```{r}
#songs_selected <- training_data %>% filter(avg_rank < 20,weeks_trending > 2)
#Lasso vars
y <- train$ranking

x <- data.matrix(train[,c("danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence","tempo")])

cv_model <- cv.glmnet(x,y,alpha = 0)

best_lambda <- cv_model$lambda.min

best_lambda

#----------------------------------------------------------------------------------------------
# LASSO Training with random song
plot(cv_model)


best_model <- glmnet(x,y,alpha = 0, lambda = best_lambda)
coef(best_model)
SongQ = "Live Well"
new = spotifyr::search_spotify(SongQ,type = "track")
id = new["id"][[1]][1]

track = get_track_audio_features(id)
track = track[c("danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence","tempo")]



new = matrix(as_vector(track),nrow = 1,ncol = 9)
predict(best_model, s = best_lambda, newx = new)
#----------------------------------------------------------------------------------------------
#use fitted best model to make predictions
y_predicted <- predict(best_model, s = best_lambda, newx = x)

sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)

#find R-Squared
rsq <- 1 - sse/sst
rsq
```



















