---
title: "DenverCharts"
author: "Zain Elsell"
date: '2022-03-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spotifyr)
library(stringr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)
library(knitr)
#install.packages("remotes")
#remotes::install_github("mvkorpel/pickURL")

```


```{r}
id ='71e950603dd64e1291d04fabafee04d9'
secret = '5331da62c4644ee887ff07216c35b183'
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
access_token
```


What this code does is using the raw html from the spotify website it gets the track IDS of the most uniquely popular songs in Denver, Colorado (only for the week of March 28, 2022) 

```{r}

#This is where the data was taken from:
url_charts_local = "https://charts.spotify.com/charts/view/citypulsetrack-denver-weekly/latest"
url_charts_login_redirct = "https://accounts.spotify.com/en/login?continue=https%3A%2F%2Fcharts.spotify.com/login"


raw_html_file_name = "Local_Pulse_March_28.txt"#For teting 
htmlVectorRaw = read_file(raw_html_file_name) #vector of every charcter in the

all_links = pickURL::pick_urls(htmlVectorRaw) # picks out all occurrences of links in the raw html code

songlinks= c()
url_pattern = "https://open.spotify.com/track/"

for(i in 1:length(all_links)){
  if(str_detect(all_links[i], url_pattern))
  {
    songlinks =c(songlinks, all_links[i])
    
  }
}


songKeys = str_replace_all(songlinks, url_pattern, "")
songKeys


# metaData = get_all_vars(data = paste0(songKeys[1]))
# 
# metaData

```

```{r}
#topFiftyDf = data.frame(songUID = songKeys, get_artist("26wuBc04catG1QQyYupr35"))#, Artist = get_artist(songlinks))
#topFiftyDf
```

```{r}
tracks <-   data.frame()


for (i in songKeys) {
  tracks <- rbind(tracks,get_track_audio_features(i))
}

names<- c()
for (i in tracks$id){
  name2<-c(get_tracks(i)[["name"]])
  names = c(names,name2)
  
}

artist_names<- c()
for (i in tracks$id){
  name2<-c(get_tracks(i)[["name"]])
  names = c(names,name2)
  
}
artist_names
tracks <- tracks %>% mutate(name = unique(names)) %>% relocate(name)
```

```{r}
tracks_copy = tracks
```

```{r}
get_tracks("26wuBc04catG1QQyYupr35")[[1]]

get_artists(get_tracks("26wuBc04catG1QQyYupr35")[[1]])[["genres"]]

```


















































































